export const jobSkills = {
  Design: [
    { label: "Adobe Photoshop", value: "adobe_photoshop" },
    { label: "Adobe Illustrator", value: "adobe_illustrator" },
    { label: "Sketch", value: "sketch" },
    { label: "Figma", value: "figma" },
    { label: "InVision", value: "invision" },
  ],
  Developer: [
    { label: "JavaScript", value: "javascript" },
    { label: "Python", value: "python" },
    { label: "Java", value: "java" },
    { label: "C#", value: "c_sharp" },
    { label: "Ruby", value: "ruby" },
    { label: "C++", value: "c_plus_plus" },
    { label: "PHP", value: "php" },
    { label: "Swift", value: "swift" },
    { label: "Kotlin", value: "kotlin" },
    { label: "TypeScript", value: "typescript" },
    { label: "Scala", value: "scala" },
    { label: "Go", value: "go" },
    { label: "Rust", value: "rust" },
    { label: "Perl", value: "perl" },
    { label: "R", value: "r" },
    { label: "SQL", value: "sql" },
    { label: "NoSQL", value: "nosql" },
    { label: "React", value: "react" },
    { label: "Angular", value: "angular" },
    { label: "Vue.js", value: "vue_js" },
    { label: "Node.js", value: "node_js" },
    { label: "Django", value: "django" },
    { label: "Flask", value: "flask" },
    { label: "Spring Boot", value: "spring_boot" },
    { label: "ASP.NET", value: "asp_net" },
    { label: "Ruby on Rails", value: "ruby_on_rails" },
    { label: "Laravel", value: "laravel" },
    { label: "Express.js", value: "express_js" },
    { label: "GraphQL", value: "graphql" },
    { label: "Docker", value: "docker" },
    { label: "Kubernetes", value: "kubernetes" },
    { label: "AWS", value: "aws" },
    { label: "Azure", value: "azure" },
    { label: "Google Cloud", value: "google_cloud" },
    { label: "Git", value: "git" },
    { label: "CI/CD", value: "ci_cd" },
    { label: "DevOps", value: "devops" },
  ],
  Management: [
    { label: "Project Management", value: "project_management" },
    { label: "Agile Methodologies", value: "agile_methodologies" },
    { label: "Scrum", value: "scrum" },
    { label: "Leadership", value: "leadership" },
    { label: "Budgeting", value: "budgeting" },
  ],
  Customer_Success: [
    { label: "Customer Relationship Management", value: "crm" },
    { label: "Technical Support", value: "technical_support" },
    { label: "Account Management", value: "account_management" },
    { label: "Client Onboarding", value: "client_onboarding" },
    { label: "Feedback Collection", value: "feedback_collection" },
  ],
  Marketing: [
    { label: "Digital Marketing", value: "digital_marketing" },
    { label: "Content Creation", value: "content_creation" },
    { label: "SEO/SEM", value: "seo_sem" },
    { label: "Social Media Marketing", value: "social_media_marketing" },
    { label: "Email Marketing", value: "email_marketing" },
  ],
  Internship: [
    { label: "Research", value: "research" },
    { label: "Data Entry", value: "data_entry" },
    { label: "Administrative Support", value: "administrative_support" },
    { label: "Social Media Handling", value: "social_media_handling" },
    { label: "Customer Service", value: "customer_service" },
  ],
} as const;
